# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'OHShareToolDemo' do
   pod 'UMengSocial', '~> 5.0'
   pod 'OHShareTool', '~> 0.1.0’
end

